title: myard.xyz
author: Benoit Myard
email: myardbenoit@gmail.com
description: >
  

lang: en

github_username: saalaa
linkedin_username: benoit-myard-805288156

theme: jekyll-theme-kagami
color_scheme: github

markdown: kramdown
destination: docs
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
